### ISSUE TITLE
is youtube source broken?

### ISSUE THREAD

**Issue by agzam** [armindarvish/consult-web#25]
Sorry, I'm a bit late to the party. I finally get to try out this thing. I'm not sure if something is missing on my setup or if this is a legit bug. I couldn't figure out how to get YouTube search. I've got the API key, etc., and `consult-web-google`, that requires similar setup worked right away.

I haven't tried to debug this yet, just reporting it in case someone comes across it.

**Comment by armindarvish** [comment]
not sure, what the issue is. The only thin I noticed was that youtube was using `consult-web-google-customsearch-key`, which should have worked anyway but if one wants to use different accounts, it would cause confusion. I fixed that now. Google and Youtube can use separate keys.


@agzam Can you set `consult-web-log-level` to `debug` and check the contents of the buffer ` *consult-web-log*`. Note the space in the buffer name. it's a hidden buffer. (or check the variable `consult-web-log-buffer-name` to see the name of the log buffer if you have set that) and see if there's any useful information in there. You can also check the url-retrieve buffers. Look for a hidden buffer called ` *http www.googleapis...*` 

**If you copy the content of either of those buffers here, make sure to remove the secret keys if any**

**Comment by avishefi** [comment]
`check-parens` on `consult-web-youtube.el` shows that the last commit removed an extra parenthesis.

**Comment by armindarvish** [comment]
@avishefi Oops! I missed a parenthesis. I fixed it now!

**Comment by agzam** [comment]
Thank you for fixing it. It works now.

**Comment by armindarvish** [comment]
@agzam By the way, I am working on introducing async sources, and etc. in async branch. This is almost a complete redesign of the whole package. So if you are just starting to test things out, you may want to look at that branch instead of develop.

**Comment by agzam** [comment]
That's cool. I'm still very new to the package and its features. At this point, I'm not even an early tester; I'm still a mere consumer. I want to find some bandwidth to explore it better and add some custom search sources. For now, I'm only using basic features.

**Comment by agzam** [comment]
Eh, what’s the worst that could happen? I already adore you for getting this started. Sure, I might be momentarily hate you if it breaks, but I’ll quickly go back to loving you once it’s up and running again.
