### ISSUE TITLE
Google source count never goes over 10

### ISSUE THREAD

**Issue by agzam** [armindarvish/consult-web#30]
If `consult-web-default-count` is set to be e.g. 15, it should fetch 15 results. Currently it gets ten.

This line seems to be incorrect:

https://github.com/armindarvish/consult-web/blob/async/sources/consult-web-google.el#L60

```
(count (min count 10))
```

**Comment by agzam** [comment]
I think some audit of `count` vars in sources would be nice. Here's my preliminary findings:

When `consult-web-default-count` is set to 30

- Brave - displays 20 lines
- Google - 10 (as reported in this issue)
- Browser History - only six, maybe that's the only what was found, perhaps this is accurate 
- DDG - only 3, as we discussed before, DuckDuckGo API is just weird, perhaps nothing is wrong with this one either
- Wikipedia - 30. Accurate
- YouTube - 30. Also accurate
- Notmuch - blows it up to 926. I guess there's no limit there at all
- GitHub - 30. Accurate

**Comment by armindarvish** [comment]
@agzam That is mostly forced by the API not by consult-omni. The line `(count (min count 10))` is there because otherwise results get lost. 
Google API will only return 10 anyway, but the consequence is that if you set count to 15 and page to 1, then some results (form 10 to 15) get lost! So in case of Google we have to max the count to 10.

**Comment by armindarvish** [comment]
In case of notmuch, we are simply reusing `consult-notmuch` and as far as I understand `consult-otmuch` does not implement the `--limit` in search. It is possible to use `notmuch` elisp package or even the underlying `notmuch` command from the command line. IT seems to have both `--limit` and `--offset` switches in the command line argument that can be used with :count and :page in consult-web. 
But I am not a user of `notmuch`. I use `mu4e` and my own `consult-mu`, so I have not really spend a lot of time trying to optimize the `onsult-web-notmuch` workflow. If I find time and if there is enough interest form users (a.k.a. some github supporters 😃), I can try to look into that.

**Comment by agzam** [comment]
> So in case of Google we have to max the count to 10.

Wait, I don't get it. How do you get more than 10 with `consult-web-google`? Are you saying that's not easily possible atm?

**Comment by armindarvish** [comment]
> > So in case of Google we have to max the count to 10.
> 
> Wait, I don't get it. How do you get more than 10 with `consult-web-google`? Are you saying that's not easily possible atm?

You cannot get more than 10, because Google API maxes the count, but you can use paging to see more results.

`search-term -- :p 1`

or

`search-term -- :n 10 :p 1` (equivalent to `search-term -- :count 10 :page 1)

The :n (or :count) is the number of items per page and :p (or :page) is the page number so the first (:count  * :page-1) will be skipped similar to what you would have seen in the old Google interface where you had multiple pages.

**Comment by armindarvish** [comment]
now moving to the new repo consult-omni. In there I already implemented a solution for notmuch, although it is not fully tested yet, and may still be buggy. Closing this here now. Feel free to reopen in [consult-omni](https://github.com/armindarvish/consult-omni) if needed.
